import { Language, RarityId } from '../types';

export const TRANSLATIONS: Record<Language, {
    UI: Record<string, string>;
    RARITY_NAMES: Record<RarityId, string>;
}> = {
    en: {
        UI: {
            ROLLS: "ROLLS",
            BEST: "BEST",
            LUCK_BOOST: "LUCK BOOST",
            INVENTORY: "INVENTORY",
            COLLECTION: "COLLECTION",
            NO_ITEMS: "No rare items found yet.",
            KEEP_SPINNING: "Keep spinning.",
            CHANCE: "CHANCE",
            READY: "READY TO INITIALIZE",
            GENERATE: "GENERATE",
            AUTO_SPIN: "AUTO SPIN",
            STOP_AUTO: "STOP AUTO",
            SYSTEM_CONFIG: "SYSTEM CONFIG",
            SPEED: "AUTO-SPIN INTERVAL",
            LUCK_MULT: "LUCK MULTIPLIER (ADMIN)",
            PRESETS: "DEBUG PRESETS",
            RESET: "RESET",
            LUCKY: "LUCKY",
            GOD_MODE: "GOD MODE",
            GUARANTEED: "GUARANTEED",
            INSPECT: "CLICK TO INSPECT",
            MOON_TRAVEL: "MOON TRAVEL",
            RETURN_EARTH: "RETURN TO EARTH",
        },
        RARITY_NAMES: {
            [RarityId.COMMON]: "Common",
            [RarityId.UNCOMMON]: "Uncommon",
            [RarityId.RARE]: "Rare",
            [RarityId.EPIC]: "Epic",
            [RarityId.LEGENDARY]: "Legendary",
            [RarityId.MYTHICAL]: "Mythical",
            [RarityId.DIVINE]: "Divine",
            [RarityId.OTHERWORLDLY]: "Otherworldly",
            [RarityId.COSMIC]: "Cosmic",
            [RarityId.EXTREME]: "Extreme",
            [RarityId.ABYSSAL]: "Abyssal",
            [RarityId.PRIMORDIAL]: "Primordial",
            [RarityId.INFINITE]: "Infinite",
            [RarityId.CHAOS]: "Chaos",
            [RarityId.THE_ONE]: "The One",
            [RarityId.MOON]: "Moon"

        }
    }

};

export const PHRASES = {
    en: {
        [RarityId.COMMON]: [
            { text: "A rusty spoon.", description: "It might have been useful once." },
            { text: "Piece of lint.", description: "Pocket debris of no value." },
            { text: "Old receipt.", description: "The ink has faded away." },
            { text: "Empty soda can.", description: "Sticky and crushed." },
            { text: "Dust bunny.", description: "It rolls across the floor." },
            { text: "Broken pencil.", description: "Pointless." },
            { text: "Withered leaf.", description: "Crunchy and brown." },
            { text: "Pebble.", description: "Just a small rock." },
            { text: "Scratched coin.", description: "You can barely see the face." },
            { text: "Used tissue.", description: "Gross." },
            { text: "Leftover pizza crust.", description: "From three days ago." },
            { text: "Unpaired sock.", description: "Where did the other one go?" },
            { text: "Tangled earbuds.", description: "Physically impossible geometry." },
            { text: "Expired coupon.", description: "10% off nothing." },
            { text: "Bubblegum wrapper.", description: "The flavor lasted 5 seconds." },
            { text: "Broken paperclip.", description: "Holding nothing together." },
            { text: "Generic NPC dialogue.", description: "Nice weather we're having." },
            { text: "Loading screen tip.", description: "Press jump to jump." },
            { text: "Plastic fork.", description: "One tine is missing." },
            { text: "Empty cardboard box.", description: "A cat would love this." },
            { text: "Used napkin", description: "Slightly stained." },
            { text: "Broken glass", description: "Sharp edges." },
            { text: "Bent nail", description: "Useless for building." },
            { text: "Bottle cap", description: "Currency in the wasteland." },
            { text: "Gum wrapper", description: "Shiny foil." },
            { text: "Sticky note", description: "Remind me later." },
            { text: "Dead battery", description: "No charge left." },
            { text: "Torn ticket", description: "Admit none." },
            { text: "Loose button", description: "Fell off a shirt." },
            { text: "Paperclip chain", description: "Office boredom." },
            { text: "Empty pen", description: "Out of ink." },
            { text: "Burnt match", description: "Already used." },
            { text: "Stale cracker", description: "Needs water." },
            { text: "Dust mite", description: "Microscopic friend." },
            { text: "Hairball", description: "From a cat." },
            { text: "Lint roller sheet", description: "Sticky." },
            { text: "Expired milk carton", description: "Do not drink." },
            { text: "Soggy cardboard", description: "Wet and mushy." },
            { text: "Rusty washer", description: "Not for cleaning." },
            { text: "Broken zipper", description: "Stuck forever." }
        ],
        [RarityId.UNCOMMON]: [
            { text: "A lucky penny.", description: "Heads up." },
            { text: "Crisp apple.", description: "Fresh from the tree." },
            { text: "Polished stone.", description: "Smooth to the touch." },
            { text: "Interesting beetle.", description: "It has shiny wings." },
            { text: "Old photograph.", description: "Faces you don't recognize." },
            { text: "Brass key.", description: "It doesn't open anything you own." },
            { text: "Silver ring.", description: "Slightly tarnished." },
            { text: "Heavy book.", description: "Full of dense text." },
            { text: "Warm socks.", description: "Comfortable." },
            { text: "Fresh coffee.", description: "Aromatic and hot." },
            { text: "Vibe check pass.", description: "You have passed." },
            { text: "Hydrated water.", description: "Now with wetness." },
            { text: "Cool stick.", description: "It looks like a gun." },
            { text: "Double rainbow.", description: "What does it mean?" },
            { text: "Found $5.", description: "Lunch is on you." },
            { text: "Perfectly toasted toast.", description: "Golden brown." },
            { text: "Full phone battery.", description: "Satisfying." },
            { text: "Green traffic light.", description: "Don't stop now." },
            { text: "Cat video.", description: "Instant serotonin." },
            { text: "Extra fry.", description: "At the bottom of the bag." },
            { text: "Shiny marble", description: "Lost your marbles?" },
            { text: "Foreign coin", description: "Worth something somewhere." },
            { text: "Cool rock", description: "It has a stripe." },
            { text: "Four-color pen", description: "Click click click." },
            { text: "Unopened soda", description: "Fizzy." },
            { text: "Fresh donut", description: "Sprinkles." },
            { text: "Working flashlight", description: "Bright idea." },
            { text: "Full lighter", description: "Fire starter." },
            { text: "Swiss army knife", description: "Has a toothpick." },
            { text: "Compass", description: "Points North." },
            { text: "Map", description: "You are here." },
            { text: "Binoculars", description: "See far." },
            { text: "Calculator", description: "80085." },
            { text: "Notepad", description: "Write it down." },
            { text: "Sketchbook", description: "Draw it out." },
            { text: "Paintbrush", description: "Happy little trees." },
            { text: "Harmonica", description: "Blues traveler." },
            { text: "Deck of cards", description: "Pick a card." },
            { text: "Dice set", description: "Roll for initiative." },
            { text: "Yo-yo", description: "Walk the dog." }
        ],
        [RarityId.RARE]: [
            { text: "Golden ticket.", description: "Admit one." },
            { text: "Four-leaf clover.", description: "Nature's luck." },
            { text: "Shiny Trading Card.", description: "Mint condition." },
            { text: "Ancient coin.", description: "From a fallen empire." },
            { text: "Message in a bottle.", description: "Sent centuries ago." },
            { text: "Fossilized amber.", description: "Life preserved." },
            { text: "Perfect snowflake.", description: "It hasn't melted." },
            { text: "Blue screen of death.", description: "Fatal system error." },
            { text: "Bitcoin wallet.", description: "Password forgotten." },
            { text: "Invisibility cloak.", description: "I can't find it." },
            { text: "Silver compass.", description: "Points to what you want most." },
            { text: "Skeleton key.", description: "Opens any door once." },
            { text: "Bag of holding.", description: "It's bigger on the inside." },
            { text: "Truth serum.", description: "Tastes like water." },
            { text: "Hover boots.", description: "Walk on air." },
            { text: "Night vision goggles.", description: "Everything is green." },
            { text: "Universal remote.", description: "Controls the universe, or just TVs." },
            { text: "Spy watch.", description: "Lasers included." },
            { text: "Cloaking device.", description: "Batteries not included." },
            { text: "Grappling hook.", description: "Climb anything." },
            { text: "Signed poster", description: "Worth a fortune." },
            { text: "First edition book", description: "Smells like old paper." },
            { text: "Vintage camera", description: "Needs film." },
            { text: "Gold watch", description: "Ticks loudly." },
            { text: "Silver locket", description: "Picture inside." },
            { text: "Pearl necklace", description: "Classy." },
            { text: "Diamond ring", description: "Forever." },
            { text: "Emerald brooch", description: "Green with envy." },
            { text: "Ruby earrings", description: "Red hot." },
            { text: "Sapphire pendant", description: "Deep blue." },
            { text: "Topaz bracelet", description: "Golden glow." },
            { text: "Opal ring", description: "Rainbow fire." },
            { text: "Amethyst necklace", description: "Royal purple." },
            { text: "Garnet pin", description: "Dark red." },
            { text: "Aquamarine charm", description: "Sea blue." },
            { text: "Peridot stud", description: "Olive green." },
            { text: "Turquoise bead", description: "Southwest style." },
            { text: "Jade bangle", description: "Lucky stone." },
            { text: "Onyx cufflink", description: "Black as night." },
            { text: "Platinum chain", description: "Heavy metal." }
        ],
        [RarityId.EPIC]: [
            { text: "Meteorite fragment.", description: "Cold to the touch, from the void." },
            { text: "Dragon egg.", description: "Warm and vibrating." },
            { text: "Laser sword.", description: "Elegant weapon." },
            { text: "Hoverboard.", description: "It actually hovers." },
            { text: "Time capsule.", description: "Do not open until 3000." },
            { text: "Genie's lamp.", description: "Three wishes remain." },
            { text: "Perpetual motion machine.", description: "It never stops." },
            { text: "Fountain of Youth water.", description: "Refreshing." },
            { text: "Teleporter pad.", description: "One way trip." },
            { text: "Gravity gun.", description: "Zero point energy field manipulator." },
            { text: "Portal gun.", description: "Now you're thinking with portals." },
            { text: "Health potion.", description: "Red and cherry flavored." },
            { text: "Mana potion.", description: "Blue and berry flavored." },
            { text: "Power armor.", description: "Fusion core required." },
            { text: "Plasma rifle.", description: "Hot to the touch." },
            { text: "Energy sword.", description: "Swish swish stab." },
            { text: "Jetpack.", description: "Don't burn your back." },
            { text: "Smart AI chip.", description: "Hello world." },
            { text: "Nano-suit.", description: "Maximum strength." },
            { text: "Cybernetic eye.", description: "Zoom and enhance." },
            { text: "Hoverboard prototype", description: "Wobbly." },
            { text: "Laser pistol", description: "Pew pew." },
            { text: "Plasma shield", description: "Blocks projectiles." },
            { text: "Anti-gravity boots", description: "Floaty steps." },
            { text: "Teleportation ring", description: "Short range only." },
            { text: "Mind-reading helmet", description: "Hear thoughts." },
            { text: "Invisibility cloak (torn)", description: "Mostly hidden." },
            { text: "Time-turner (broken)", description: "Stuck in a loop." },
            { text: "Lightsaber (toy)", description: "Plastic blade." },
            { text: "Phaser (stun only)", description: "Set to stun." },
            { text: "Tricorder", description: "Scanning..." },
            { text: "Sonic screwdriver", description: "Buzzing noise." },
            { text: "Portal gun (empty)", description: "No gel." },
            { text: "Gravity gun (weak)", description: "Lifts cans." },
            { text: "Energy sword (dull)", description: "Needs sharpening." },
            { text: "Power armor (rusty)", description: "Squeaky joints." },
            { text: "Jetpack (low fuel)", description: "Short hops." },
            { text: "AI chip (glitchy)", description: "Sarcastic." },
            { text: "Nano-suit (ripped)", description: "Leaking nanites." },
            { text: "Cybernetic arm", description: "Strong grip." }
        ],
        [RarityId.LEGENDARY]: [
            { text: "Excalibur's hilt.", description: "The blade is missing." },
            { text: "Pandora's Box.", description: "Hope is still inside." },
            { text: "Holy Grail.", description: "Choose wisely." },
            { text: "Mjolnir.", description: "Are you worthy?" },
            { text: "The One Ring.", description: "Precious." },
            { text: "Infinity Gauntlet.", description: "Snap." },
            { text: "Trident of Poseidon.", description: "Control the seas." },
            { text: "Zeus's Thunderbolt.", description: "Shocking power." },
            { text: "Hades' Helm.", description: "Invisibility." },
            { text: "Hermes' Sandals.", description: "Gotta go fast." },
            { text: "Aegis Shield.", description: "Unbreakable." },
            { text: "Golden Fleece.", description: "Heals all wounds." },
            { text: "Spear of Destiny.", description: "Pierces anything." },
            { text: "Ark of the Covenant.", description: "Keep it closed." },
            { text: "Necronomicon.", description: "Don't read aloud." },
            { text: "Book of Thoth.", description: "Knowledge of the gods." },
            { text: "Tablet of Destinies.", description: "Control the fate of the world." },
            { text: "Philosopher's Stone.", description: "Immortality and gold." },
            { text: "Excalibur.", description: "King of swords." },
            { text: "Durandal.", description: "Indestructible sword." },
            { text: "Excalibur (Reforged)", description: "Sharp again." },
            { text: "Mjolnir (Replica)", description: "Heavy." },
            { text: "Gungnir", description: "Never misses." },
            { text: "Trident", description: "Three points." },
            { text: "Thunderbolt", description: "Lightning strike." },
            { text: "Helm of Darkness", description: "Unseen." },
            { text: "Winged Sandals", description: "Fly high." },
            { text: "Aegis", description: "Face of Medusa." },
            { text: "Golden Fleece", description: "Wooly gold." },
            { text: "Spear of Destiny", description: "Fate piercer." },
            { text: "Ark", description: "Do not touch." },
            { text: "Necronomicon (Page)", description: "Madness." },
            { text: "Book of Thoth (Chapter)", description: "Magic words." },
            { text: "Tablet of Destinies (Fragment)", description: "Rule the world." },
            { text: "Philosopher's Stone (Shard)", description: "Red dust." },
            { text: "Kusanagi", description: "Grass cutter." },
            { text: "Masamune", description: "Perfect blade." },
            { text: "Muramasa", description: "Cursed blade." },
            { text: "Honjo Masamune", description: "Lost sword." },
            { text: "Gae Bolg", description: "Barbed spear." }
        ],
        [RarityId.MYTHICAL]: [
            { text: "A whisper from the void.", description: "You shouldn't have heard that." },
            { text: "Phoenix Down.", description: "Revives the fallen." },
            { text: "Unicorn.", description: "A horse with a point." },
            { text: "Kraken's tentacle.", description: "Still wriggling." },
            { text: "Medusa's gaze.", description: "Don't look." },
            { text: "Eye of Ra.", description: "Power of the sun." },
            { text: "Anubis' Scales.", description: "Weighing the heart." },
            { text: "Osiris' Flail.", description: "Rule the afterlife." },
            { text: "Isis' Knot.", description: "Magical protection." },
            { text: "Horus' Eye.", description: "Protection and power." },
            { text: "Thor's Belt.", description: "Double strength." },
            { text: "Odin's Spear.", description: "Never misses." },
            { text: "Freya's Necklace.", description: "Most beautiful jewelry." },
            { text: "Loki's Mask.", description: "Change shape." },
            { text: "Heimdall's Horn.", description: "Sound the alarm." },
            { text: "Tyr's Hand.", description: "Sacrifice for justice." },
            { text: "Fenrir's Chain.", description: "Unbreakable bond." },
            { text: "Jormungandr's Scale.", description: "World serpent." },
            { text: "Ymir's Flesh.", description: "Earth itself." },
            { text: "Valkyrie's Wings.", description: "Flight of the chooser." },
            { text: "Unicorn Horn", description: "Purifies water." },
            { text: "Dragon Scale", description: "Harder than steel." },
            { text: "Phoenix Feather", description: "Warm to the touch." },
            { text: "Griffin Claw", description: "Sharp and hooked." },
            { text: "Mermaid Tear", description: "Turns to pearl." },
            { text: "Basilisk Eye", description: "Petrifying gaze." },
            { text: "Chimera Tail", description: "Venomous barb." },
            { text: "Hydra Head", description: "Two grow back." },
            { text: "Kraken Tentacle", description: "Sucker punched." },
            { text: "Yeti Fur", description: "Warm in the cold." },
            { text: "Sasquatch Footprint", description: "Big foot." },
            { text: "Chupacabra Tooth", description: "Goat sucker." },
            { text: "Jackalope Antler", description: "Rabbit with horns." },
            { text: "Minotaur Horn", description: "Lost in the maze." },
            { text: "Centaur Hoof", description: "Half horse." },
            { text: "Siren Song (Bottled)", description: "Don't open it." },
            { text: "Medusa Snake", description: "Hissing hair." },
            { text: "Cerberus Collar", description: "Three heads." },
            { text: "Pegasus Wing", description: "Flying horse." },
            { text: "Sphinx Riddle", description: "Answer or die." }
        ],
        [RarityId.DIVINE]: [
            { text: "Angelic resonance.", description: "A frequency that heals the spirit." },
            { text: "Burning bush.", description: "It speaks." },
            { text: "Zeus's lightning.", description: "High voltage." },
            { text: "Halo.", description: "Floating above your head." },
            { text: "Voice of God.", description: "Command creation." },
            { text: "Hand of God.", description: "Intervention." },
            { text: "Breath of Life.", description: "Animation." },
            { text: "Soul of the World.", description: "Anima Mundi." },
            { text: "Light of Creation.", description: "Let there be light." },
            { text: "Darkness of the Void.", description: "Before the beginning." },
            { text: "Tree of Life Branch.", description: "Healing." },
            { text: "Tree of Knowledge Fruit.", description: "Wisdom." },
            { text: "Garden of Eden Dirt.", description: "Fertility." },
            { text: "Noah's Ark Wood.", description: "Salvation." },
            { text: "Moses' Staff.", description: "Part the seas." },
            { text: "David's Sling.", description: "Giant slayer." },
            { text: "Solomon's Ring.", description: "Control demons." },
            { text: "Elijah's Chariot.", description: "Fire ride." },
            { text: "Metatron's Cube.", description: "Sacred geometry." },
            { text: "Gabriel's Horn.", description: "The end is nigh." },
            { text: "Halo (Broken)", description: "Fallen angel." },
            { text: "Angel Wing", description: "Feather of light." },
            { text: "Demon Horn", description: "Smells of sulfur." },
            { text: "Holy Water", description: "Burns evil." },
            { text: "Hellfire Ember", description: "Never goes out." },
            { text: "Ambrosia", description: "Food of the gods." },
            { text: "Nectar", description: "Drink of the gods." },
            { text: "Manna", description: "Bread from heaven." },
            { text: "Forbidden Fruit", description: "Knowledge of good and evil." },
            { text: "Burning Bush (Branch)", description: "Still burning." },
            { text: "Noah's Ark (Plank)", description: "Gopher wood." },
            { text: "Commandment Tablet", description: "Stone rules." },
            { text: "Golden Calf (Fragment)", description: "False idol." },
            { text: "Holy Grail (Cup)", description: "Choose wisely." },
            { text: "Spear of Longinus (Tip)", description: "Destiny." },
            { text: "True Cross (Splinter)", description: "Relic." },
            { text: "Shroud of Turin (Thread)", description: "Image." },
            { text: "Crown of Thorns", description: "Painful." },
            { text: "Sacred Heart", description: "Burning love." },
            { text: "Divine Spark", description: "Soul fire." }
        ],
        [RarityId.OTHERWORLDLY]: [
            { text: "Non-euclidean shape.", description: "It has more angles than it should." },
            { text: "Tesseract.", description: "A cube within a cube." },
            { text: "Klein bottle.", description: "One sided surface." },
            { text: "Cthulhu's dream.", description: "Madness induces." },
            { text: "Alien Artifact.", description: "Unknown origin." },
            { text: "UFO Debris.", description: "Advanced alloy." },
            { text: "Grey's Skull.", description: "Large eyes." },
            { text: "Crop Circle Design.", description: "Message from above." },
            { text: "Area 51 Keycard.", description: "Top secret." },
            { text: "Element 115.", description: "Fuel for the unknown." },
            { text: "Zero Point Module.", description: "Infinite energy." },
            { text: "Warp Drive Core.", description: "Faster than light." },
            { text: "Stargate Address.", description: "7 symbols." },
            { text: "Tardis Key.", description: "Time and relative dimension." },
            { text: "Sonic Screwdriver.", description: "Does everything." },
            { text: "Psychic Paper.", description: "Shows what you want." },
            { text: "Vortex Manipulator.", description: "Cheap time travel." },
            { text: "Neuralyzer.", description: "Flash of light." },
            { text: "Lightsaber Crystal.", description: "Kyber." },
            { text: "Holocron.", description: "Jedi knowledge." },
            { text: "Alien Skull", description: "Elongated." },
            { text: "UFO Part", description: "Unknown metal." },
            { text: "Crop Circle Soil", description: "Bent stalks." },
            { text: "Moon Rock", description: "From the Sea of Tranquility." },
            { text: "Mars Dust", description: "Red oxide." },
            { text: "Space Suit Helmet", description: "Cracked visor." },
            { text: "Ray Gun", description: "Zap." },
            { text: "Teleporter Pad", description: "Energize." },
            { text: "Grey Alien DNA", description: "Helix." },
            { text: "Reptilian Scale", description: "Green and slimy." },
            { text: "Men in Black Neuralyzer", description: "Flash." },
            { text: "Area 51 ID Badge", description: "Clearance Level 9." },
            { text: "Roswell Debris", description: "Memory metal." },
            { text: "Wow! Signal Recording", description: "6EQUJ5." },
            { text: "Dyson Sphere Fragment", description: "Star energy." },
            { text: "Wormhole Key", description: "Open the gate." },
            { text: "Tesseract", description: "4D cube." },
            { text: "Hypercube", description: "Folded space." },
            { text: "Mobius Strip", description: "One side." },
            { text: "Klein Bottle", description: "No inside." }
        ],
        [RarityId.COSMIC]: [
            { text: "Birth of a star.", description: "Fusion ignition sequence." },
            { text: "Supernova.", description: "Brighter than a galaxy." },
            { text: "Quasar.", description: "The beacon of the universe." },
            { text: "Galaxy in a Jar.", description: "Spinning spiral." },
            { text: "Nebula Cloud.", description: "Star nursery." },
            { text: "Black Hole Event Horizon.", description: "Point of no return." },
            { text: "White Hole.", description: "Pushing everything away." },
            { text: "Wormhole Generator.", description: "Shortcut." },
            { text: "Dark Energy Canister.", description: "Expanding universe." },
            { text: "Cosmic String.", description: "Crack in spacetime." },
            { text: "Pulsar Core.", description: "Spinning fast." },
            { text: "Quasar Beam.", description: "Brightest light." },
            { text: "Magnetar Field.", description: "Magnetic power." },
            { text: "Supernova Remnant.", description: "Explosive aftermath." },
            { text: "Gamma Ray Burst.", description: "Deadly radiation." },
            { text: "Cosmic Background Radiation.", description: "Echo of the bang." },
            { text: "Multiverse Map.", description: "Infinite paths." },
            { text: "Time Crystal.", description: "Repeating in time." },
            { text: "Strangelet.", description: "Dangerous matter." },
            { text: "Vacuum Decay Trigger.", description: "End of everything." },
            { text: "Star Dust", description: "We are made of this." },
            { text: "Nebula Gas", description: "Colorful cloud." },
            { text: "Supernova Remnant", description: "Explosion echo." },
            { text: "Black Hole Event Horizon", description: "No return." },
            { text: "Quasar Beam", description: "Blinding light." },
            { text: "Pulsar Signal", description: "Beep beep." },
            { text: "Dark Matter", description: "Invisible mass." },
            { text: "Dark Energy", description: "Expansion force." },
            { text: "Cosmic Ray", description: "High energy." },
            { text: "Gamma Ray Burst", description: "Sterilizer." },
            { text: "Neutron Star Core", description: "Dense." },
            { text: "White Dwarf Matter", description: "Degenerate." },
            { text: "Red Giant Atmosphere", description: "Expanded." },
            { text: "Planetary Ring", description: "Ice and rock." },
            { text: "Asteroid Belt Rock", description: "Drifting." },
            { text: "Comet Tail", description: "Ice trail." },
            { text: "Solar Flare", description: "Magnetic storm." },
            { text: "Galaxy Spiral", description: "Rotating arms." },
            { text: "Universe Expansion", description: "Faster and faster." },
            { text: "Big Bang Echo", description: "CMB." }
        ],
        [RarityId.EXTREME]: [
            { text: "The concept of time.", description: "It flows only forward." },
            { text: "Schrödinger's Cat.", description: "Alive and dead." },
            { text: "Reality Anchor.", description: "Hold it together." },
            { text: "Dimension Slicer.", description: "Cut through space." },
            { text: "Time Dilation Field.", description: "Slow down." },
            { text: "Quantum Entangler.", description: "Spooky action." },
            { text: "Probability Drive.", description: "Improbability." },
            { text: "Entropy Reverser.", description: "Order from chaos." },
            { text: "Physics Breaker.", description: "Ignore the laws." },
            { text: "Logic Bomb.", description: "Crash reality." },
            { text: "Paradox Generator.", description: "True and false." },
            { text: "Causality Loop.", description: "Effect before cause." },
            { text: "Infinity Loop.", description: "Never ending." },
            { text: "Singularity Point.", description: "Infinite density." },
            { text: "Big Bang Spark.", description: "Ignition." },
            { text: "Big Crunch Trigger.", description: "Collapse." },
            { text: "Heat Death Shield.", description: "Survive the cold." },
            { text: "False Vacuum Stabilizer.", description: "Prevent the end." },
            { text: "Simulation Glitch.", description: "Pixelated." },
            { text: "Developer Console.", description: "Read only." },
            { text: "Absolute Zero", description: "0 Kelvin." },
            { text: "Planck Temperature", description: "Hot limit." },
            { text: "Speed of Light", description: "c." },
            { text: "Infinite Mass", description: "Heavy." },
            { text: "Singularity", description: "Point." },
            { text: "Vacuum Decay", description: "Bubble of death." },
            { text: "False Vacuum", description: "Unstable." },
            { text: "Strange Matter", description: "Contagious." },
            { text: "Antimatter", description: "Explosive." },
            { text: "Negative Mass", description: "Push me pull you." },
            { text: "Tachyon", description: "Backwards in time." },
            { text: "Graviton", description: "Force carrier." },
            { text: "Higgs Boson", description: "God particle." },
            { text: "Quantum Entanglement", description: "Spooky." },
            { text: "Superposition", description: "Both states." },
            { text: "Schrodinger's Cat (Alive)", description: "Meow." },
            { text: "Schrodinger's Cat (Dead)", description: "Silence." },
            { text: "Maxwell's Demon", description: "Sorting entropy." },
            { text: "Laplace's Demon", description: "Knows all." },
            { text: "Roko's Basilisk", description: "Don't think about it." }
        ],
        [RarityId.ABYSSAL]: [
            { text: "The silence before creation.", description: "Absolute quiet." },
            { text: "The void.", description: "It stares back." },
            { text: "Void Heart.", description: "Beating darkness." },
            { text: "Shadow Essence.", description: "Pure dark." },
            { text: "Abyssal Gaze.", description: "Stares back." },
            { text: "Nothingness.", description: "Absolute." },
            { text: "Null Space.", description: "Does not exist." },
            { text: "Void Walker's Cloak.", description: "Step through shadow." },
            { text: "Eldritch Tentacle.", description: "Wriggling." },
            { text: "Cosmic Horror.", description: "Fear incarnate." },
            { text: "Madness Mantra.", description: "Unspeakable." },
            { text: "Forbidden Knowledge.", description: "Melt your mind." },
            { text: "Non-existence.", description: "Gone." },
            { text: "Anti-Life Equation.", description: "Control." },
            { text: "Death's Scythe.", description: "Reap." },
            { text: "Soul Eater.", description: "Hungry." },
            { text: "Demon Core.", description: "Click click." },
            { text: "Hellfire.", description: "Eternal burn." },
            { text: "Cursed Artifact.", description: "Bad luck." },
            { text: "Pandemonium.", description: "Chaos capital." },
            { text: "Void Essence", description: "Concentrated nothing." },
            { text: "Shadow Shard", description: "Sharp darkness." },
            { text: "Dark Soul", description: "Lost." },
            { text: "Abyssal Pearl", description: "Black shine." },
            { text: "Black Diamond", description: "Hard dark." },
            { text: "Obsidian Mirror", description: "Reflects nightmares." },
            { text: "Nightmare Fuel", description: "High octane fear." },
            { text: "Terror Tear", description: "Salty fear." },
            { text: "Despair Dust", description: "Choking sadness." },
            { text: "Gloom Gem", description: "Dim light." },
            { text: "Hollow Bone", description: "Echoes." },
            { text: "Empty Vial", description: "Held souls." },
            { text: "Silent Bell", description: "No sound." },
            { text: "Blind Eye", description: "Sees nothing." },
            { text: "Deaf Ear", description: "Hears nothing." },
            { text: "Mute Mouth", description: "Says nothing." },
            { text: "Cold Fire", description: "Freezing burn." },
            { text: "Liquid Darkness", description: "Drink it." },
            { text: "Solid Shadow", description: "Heavy." },
            { text: "Void Key", description: "Unlocks nothing." }
        ],
        [RarityId.PRIMORDIAL]: [
            { text: "The first breath.", description: "Inhale life.", cutscenePhrase: "INHALING EXISTENCE..." },
            { text: "The First Sound.", description: "Om." },
            { text: "The First Light.", description: "Photon." },
            { text: "The First Matter.", description: "Atom." },
            { text: "The First Thought.", description: "Idea." },
            { text: "The First Dream.", description: "Sleep." },
            { text: "The First Nightmare.", description: "Fear." },
            { text: "The First Love.", description: "Bond." },
            { text: "The First Hate.", description: "Conflict." },
            { text: "The First Life.", description: "Cell." },
            { text: "The First Death.", description: "End." },
            { text: "Chaos Egg.", description: "Origin." },
            { text: "Order Crystal.", description: "Structure." },
            { text: "Time's Origin.", description: "Start clock." },
            { text: "Space's Center.", description: "Point zero." },
            { text: "Reality's Seed.", description: "Grow world." },
            { text: "Dimension Zero.", description: "Dot." },
            { text: "The Architect's Plan.", description: "Blueprint." },
            { text: "The Weaver's Thread.", description: "Fate." },
            { text: "The Sculptor's Clay.", description: "Form." },
            { text: "First Flame", description: "Ignition." },
            { text: "Original Water", description: "Source." },
            { text: "Ancient Earth", description: "Foundation." },
            { text: "Primordial Air", description: "Breath." },
            { text: "Chaos Seed", description: "Potential." },
            { text: "Life Spark", description: "Alive." },
            { text: "Death Rattle", description: "Final." },
            { text: "Time Sand", description: "Flow." },
            { text: "Space Dust", description: "Expansion." },
            { text: "Matter Mote", description: "Solid." },
            { text: "Energy Orb", description: "Power." },
            { text: "Spirit Stone", description: "Ghost." },
            { text: "Soul Shard", description: "Fragment." },
            { text: "Mind Gem", description: "Thought." },
            { text: "Body Bone", description: "Structure." },
            { text: "Blood Drop", description: "Vitality." },
            { text: "Tear Drop", description: "Emotion." },
            { text: "Sweat Drop", description: "Effort." },
            { text: "Breath Puff", description: "Life." },
            { text: "Creation Spark", description: "Bang." }
        ],
        [RarityId.INFINITE]: [
            { text: "Everything everywhere all at once.", description: "Total saturation.", cutscenePhrase: "TOTAL SATURATION" },
            { text: "Infinity Symbol.", description: "Loop." },
            { text: "Moebius Strip.", description: "One side." },
            { text: "Ouroboros.", description: "Snake eating tail." },
            { text: "Klein Bottle.", description: "No inside." },
            { text: "Fractal Pattern.", description: "Self similar." },
            { text: "Mandelbrot Set.", description: "Complex." },
            { text: "Julia Set.", description: "Chaos." },
            { text: "Golden Ratio.", description: "Phi." },
            { text: "Pi.", description: "Never ending." },
            { text: "E.", description: "Growth." },
            { text: "Fibonacci Sequence.", description: "Nature." },
            { text: "Akashic Records.", description: "All memory." },
            { text: "Omniscience.", description: "All knowing." },
            { text: "Omnipotence.", description: "All powerful." },
            { text: "Omnipresence.", description: "Everywhere." },
            { text: "Eternity.", description: "Forever." },
            { text: "Destiny.", description: "Written." },
            { text: "Fate.", description: "Unavoidable." },
            { text: "Karma.", description: "Return." },
            { text: "Mobius Loop", description: "Twist." },
            { text: "Klein Bottle (Perfect)", description: "Manifold." },
            { text: "Ouroboros Scale", description: "Cycle." },
            { text: "Fractal Flower", description: "Zoom in." },
            { text: "Recursive Mirror", description: "Infinite reflection." },
            { text: "Endless Knot", description: "Tied forever." },
            { text: "Eternal Flame", description: "Always burning." },
            { text: "Timeless Watch", description: "No hands." },
            { text: "Spaceless Box", description: "Fits everything." },
            { text: "Limitless Potion", description: "Drink forever." },
            { text: "Boundless Book", description: "Read forever." },
            { text: "Measureless Ruler", description: "No numbers." },
            { text: "Countless Coins", description: "Rich." },
            { text: "Bottomless Pit (Portable)", description: "Don't fall." },
            { text: "Ceaseless Wind", description: "Blows forever." },
            { text: "Unending Song", description: "Earworm." },
            { text: "Immortal Jellyfish", description: "Reborn." },
            { text: "Undying Phoenix", description: "Rise again." },
            { text: "Everlasting Gobstopper", description: "Sweet." },
            { text: "Infinite Pizza", description: "One more slice." }
        ],
        [RarityId.CHAOS]: [
            { text: "Entropy unleashed.", description: "Decay accelerates.", cutscenePhrase: "UNBINDING PHYSICS" },
            { text: "Pure Chaos.", description: "Unpredictable." },
            { text: "Randomness.", description: "No pattern." },
            { text: "Discord.", description: "No harmony." },
            { text: "Anarchy.", description: "No rules." },
            { text: "Disorder.", description: "Mess." },
            { text: "Entropy Max.", description: "Heat death." },
            { text: "Quantum Foam.", description: "Bubbling." },
            { text: "Schrodinger's Box.", description: "Cat inside." },
            { text: "Heisenberg's Compensator.", description: "Uncertainty." },
            { text: "Butterfly Effect.", description: "Storm trigger." },
            { text: "Murphy's Law.", description: "Worst case." },
            { text: "Strange Attractor.", description: "Chaos theory." },
            { text: "Bifurcation.", description: "Split." },
            { text: "Turbulence.", description: "Rough flow." },
            { text: "Noise.", description: "Static." },
            { text: "Distortion.", description: "Warped." },
            { text: "Glitch.", description: "Bug." },
            { text: "Error.", description: "Mistake." },
            { text: "Crash.", description: "System down." },
            { text: "Entropy Orb", description: "Disorder." },
            { text: "Discord Apple", description: "For the fairest." },
            { text: "Anarchy Flag", description: "No gods no masters." },
            { text: "Random Number Generator", description: "RNG." },
            { text: "Glitch in the Matrix", description: "Dejavu." },
            { text: "Broken Physics", description: "Floating." },
            { text: "Undefined Variable", description: "NaN." },
            { text: "Segmentation Fault", description: "Core dump." },
            { text: "Stack Overflow", description: "Too deep." },
            { text: "Blue Screen", description: "Fatal." },
            { text: "Kernel Panic", description: "Reboot." },
            { text: "404 Error", description: "Not found." },
            { text: "500 Error", description: "Server error." },
            { text: "Missing Texture", description: "Purple checker." },
            { text: "Z-Fighting", description: "Flickering." },
            { text: "Clipping Error", description: "Stuck in wall." },
            { text: "Floating Point Error", description: "Rounding." },
            { text: "Race Condition", description: "Who's first?" },
            { text: "Deadlock", description: "Stuck." },
            { text: "Memory Leak", description: "Draining." }
        ],

        [RarityId.THE_ONE]: [
            { text: "YOU ARE THE DEVELOPER.", description: "Access granted.", cutscenePhrase: "ACCESS GRANTED" },
            { text: "Admin Access.", description: "Root." },
            { text: "God Mode.", description: "Invincible." },
            { text: "Creative Mode.", description: "Build." },
            { text: "Source Code.", description: "The matrix." },
            { text: "The Developer.", description: "Creator." },
            { text: "The Player.", description: "You." },
            { text: "The End.", description: "Credits." },
            { text: "The Beginning.", description: "Restart." },
            { text: "Alpha.", description: "First." },
            { text: "Omega.", description: "Last." },
            { text: "Everything.", description: "All." },
            { text: "Nothing.", description: "None." },
            { text: "Yes.", description: "Positive." },
            { text: "No.", description: "Negative." },
            { text: "True.", description: "Boolean." },
            { text: "False.", description: "Boolean." },
            { text: "0.", description: "Binary." },
            { text: "1.", description: "Binary." },
            { text: "The Answer.", description: "42." },
            { text: "The Question", description: "Unknown." },
            { text: "The Truth", description: "Out there." },
            { text: "The Lie", description: "Cake." },
            { text: "The Everything", description: "Bagel." },
            { text: "The Nothing", description: "Gmork." },
            { text: "The Creator", description: "Made this." },
            { text: "The Destroyer", description: "Ended this." },
            { text: "The Observer", description: "Watching." },
            { text: "The Dreamer", description: "Sleeping." },
            { text: "The Waker", description: "Up." },
            { text: "The Code", description: "Binary." },
            { text: "The Glitch", description: "Bug." },
            { text: "You", description: "Player." },
            { text: "Me", description: "AI." },
            { text: "Us", description: "Together." },
            { text: "Them", description: "Others." },
            { text: "It", description: "Thing." },
            { text: "That", description: "Other thing." },
            { text: "This", description: "Here." },
            { text: "Now", description: "Time." }
        ],


    }

};
