import { RarityId, RarityTier, Language, ItemData } from './types';

export const RARITY_TIERS: Record<RarityId, RarityTier> = {
  [RarityId.COMMON]: {
    id: RarityId.COMMON,
    name: "Common",
    probability: 5,
    color: "border-gray-600",
    textColor: "text-gray-400",
    shadowColor: "rgba(156, 163, 175, 0)",
  },
  [RarityId.UNCOMMON]: {
    id: RarityId.UNCOMMON,
    name: "Uncommon",
    probability: 20,
    color: "border-green-600",
    textColor: "text-green-400",
    shadowColor: "rgba(74, 222, 128, 0.2)",
  },
  [RarityId.RARE]: {
    id: RarityId.RARE,
    name: "Rare",
    probability: 100,
    color: "border-blue-600",
    textColor: "text-blue-400",
    shadowColor: "rgba(96, 165, 250, 0.3)",
  },
  [RarityId.EPIC]: {
    id: RarityId.EPIC,
    name: "Epic",
    probability: 500,
    color: "border-purple-600",
    textColor: "text-purple-400",
    shadowColor: "rgba(192, 132, 252, 0.4)",
  },
  [RarityId.LEGENDARY]: {
    id: RarityId.LEGENDARY,
    name: "Legendary",
    probability: 2500,
    color: "border-yellow-600",
    textColor: "text-yellow-400",
    shadowColor: "rgba(250, 204, 21, 0.5)",
  },
  [RarityId.MYTHICAL]: {
    id: RarityId.MYTHICAL,
    name: "Mythical",
    probability: 12500,
    color: "border-pink-600",
    textColor: "text-pink-400",
    shadowColor: "rgba(244, 114, 182, 0.5)",
  },
  [RarityId.DIVINE]: {
    id: RarityId.DIVINE,
    name: "Divine",
    probability: 100000,
    color: "border-cyan-500",
    textColor: "text-cyan-300",
    shadowColor: "rgba(103, 232, 249, 0.6)",
    animate: true,
  },
  [RarityId.OTHERWORLDLY]: {
    id: RarityId.OTHERWORLDLY,
    name: "Otherworldly",
    probability: 500000,
    color: "border-indigo-500",
    textColor: "text-indigo-300",
    shadowColor: "rgba(165, 180, 252, 0.6)",
    animate: true,
  },
  [RarityId.COSMIC]: {
    id: RarityId.COSMIC,
    name: "Cosmic",
    probability: 2500000,
    color: "border-violet-500",
    textColor: "text-violet-300",
    shadowColor: "rgba(196, 181, 253, 0.7)",
    animate: true,
  },
  [RarityId.EXTREME]: {
    id: RarityId.EXTREME,
    name: "Extreme",
    probability: 10000000,
    color: "border-red-600",
    textColor: "text-red-500",
    shadowColor: "rgba(239, 68, 68, 0.8)",
    animate: true,
  },
  [RarityId.ABYSSAL]: {
    id: RarityId.ABYSSAL,
    name: "Abyssal",
    probability: 50000000,
    color: "border-slate-800",
    textColor: "text-slate-200",
    shadowColor: "rgba(15, 23, 42, 0.9)",
    animate: true,
  },
  [RarityId.PRIMORDIAL]: {
    id: RarityId.PRIMORDIAL,
    name: "Primordial",
    probability: 250000000,
    color: "border-orange-600",
    textColor: "text-orange-500",
    shadowColor: "rgba(249, 115, 22, 0.9)",
    animate: true,
  },
  [RarityId.INFINITE]: {
    id: RarityId.INFINITE,
    name: "Infinite",
    probability: 1000000000,
    color: "border-teal-400",
    textColor: "text-teal-200",
    shadowColor: "rgba(45, 212, 191, 1)",
    animate: true,
  },
  [RarityId.CHAOS]: {
    id: RarityId.CHAOS,
    name: "Chaos",
    probability: 10000000000,
    color: "border-fuchsia-600",
    textColor: "text-fuchsia-500",
    shadowColor: "rgba(217, 70, 239, 1)",
    animate: true,
  },
  [RarityId.THE_ONE]: {
    id: RarityId.THE_ONE,
    name: "The One",
    probability: 1000000000000,
    color: "border-white",
    textColor: "text-white",
    shadowColor: "rgba(255, 255, 255, 1)",
    animate: true,
  },
};

// --- LOCALIZATION ---

export const TRANSLATIONS: Record<Language, {
  UI: Record<string, string>;
  RARITY_NAMES: Record<RarityId, string>;
}> = {
  en: {
    UI: {
      ROLLS: "ROLLS",
      BEST: "BEST",
      LUCK_BOOST: "LUCK BOOST",
      INVENTORY: "INVENTORY",
      COLLECTION: "COLLECTION",
      NO_ITEMS: "No rare items found yet.",
      KEEP_SPINNING: "Keep spinning.",
      CHANCE: "CHANCE",
      READY: "READY TO INITIALIZE",
      GENERATE: "GENERATE",
      AUTO_SPIN: "AUTO SPIN",
      STOP_AUTO: "STOP AUTO",
      SYSTEM_CONFIG: "SYSTEM CONFIG",
      SPEED: "AUTO-SPIN INTERVAL",
      LUCK_MULT: "LUCK MULTIPLIER (ADMIN)",
      PRESETS: "DEBUG PRESETS",
      RESET: "RESET",
      LUCKY: "LUCKY",
      GOD_MODE: "GOD MODE",
      GUARANTEED: "GUARANTEED",
      INSPECT: "CLICK TO INSPECT"
    },
    RARITY_NAMES: {
      [RarityId.COMMON]: "Common",
      [RarityId.UNCOMMON]: "Uncommon",
      [RarityId.RARE]: "Rare",
      [RarityId.EPIC]: "Epic",
      [RarityId.LEGENDARY]: "Legendary",
      [RarityId.MYTHICAL]: "Mythical",
      [RarityId.DIVINE]: "Divine",
      [RarityId.OTHERWORLDLY]: "Otherworldly",
      [RarityId.COSMIC]: "Cosmic",
      [RarityId.EXTREME]: "Extreme",
      [RarityId.ABYSSAL]: "Abyssal",
      [RarityId.PRIMORDIAL]: "Primordial",
      [RarityId.INFINITE]: "Infinite",
      [RarityId.CHAOS]: "Chaos",
      [RarityId.THE_ONE]: "The One"
    }
  },
  it: {
    UI: {
      ROLLS: "TIRI",
      BEST: "MIGLIORE",
      LUCK_BOOST: "FORTUNA EXTRA",
      INVENTORY: "INVENTARIO",
      COLLEZIONE: "COLLEZIONE",
      NO_ITEMS: "Nessun oggetto raro trovato.",
      KEEP_SPINNING: "Continua a girare.",
      CHANCE: "PROBABILITÀ",
      READY: "PRONTO",
      GENERATE: "GENERA",
      AUTO_SPIN: "AUTO GIRO",
      STOP_AUTO: "STOP AUTO",
      SYSTEM_CONFIG: "CONFIG SISTEMA",
      SPEED: "VELOCITÀ AUTO-GIRO",
      LUCK_MULT: "MOLTIPLICATORE FORTUNA",
      PRESETS: "PREIMPOSTAZIONI DEBUG",
      RESET: "RESET",
      LUCKY: "FORTUNATO",
      GOD_MODE: "MODALITÀ DIO",
      GUARANTEED: "GARANTITO",
      INSPECT: "CLICCA PER ISPEZIONARE"
    },
    RARITY_NAMES: {
      [RarityId.COMMON]: "Comune",
      [RarityId.UNCOMMON]: "Non Comune",
      [RarityId.RARE]: "Raro",
      [RarityId.EPIC]: "Epico",
      [RarityId.LEGENDARY]: "Leggendario",
      [RarityId.MYTHICAL]: "Mitico",
      [RarityId.DIVINE]: "Divino",
      [RarityId.OTHERWORLDLY]: "Dell'Altromondo",
      [RarityId.COSMIC]: "Cosmico",
      [RarityId.EXTREME]: "Estremo",
      [RarityId.ABYSSAL]: "Abissale",
      [RarityId.PRIMORDIAL]: "Primordiale",
      [RarityId.INFINITE]: "Infinito",
      [RarityId.CHAOS]: "Caos",
      [RarityId.THE_ONE]: "L'Unico"
    }
  }
};

const PHRASES_EN: Record<RarityId, ItemData[]> = {
  [RarityId.COMMON]: [
    { text: "A rusty spoon.", description: "It might have been useful once." },
    { text: "Piece of lint.", description: "Pocket debris of no value." },
    { text: "Old receipt.", description: "The ink has faded away." },
    { text: "Empty soda can.", description: "Sticky and crushed." },
    { text: "Dust bunny.", description: "It rolls across the floor." },
    { text: "Broken pencil.", description: "Pointless." },
    { text: "Withered leaf.", description: "Crunchy and brown." },
    { text: "Pebble.", description: "Just a small rock." },
    { text: "Scratched coin.", description: "You can barely see the face." },
    { text: "Used tissue.", description: "Gross." }
  ],
  [RarityId.UNCOMMON]: [
    { text: "A lucky penny.", description: "Heads up." },
    { text: "Crisp apple.", description: "Fresh from the tree." },
    { text: "Polished stone.", description: "Smooth to the touch." },
    { text: "Interesting beetle.", description: "It has shiny wings." },
    { text: "Old photograph.", description: "Faces you don't recognize." },
    { text: "Brass key.", description: "It doesn't open anything you own." },
    { text: "Silver ring.", description: "Slightly tarnished." },
    { text: "Heavy book.", description: "Full of dense text." },
    { text: "Warm socks.", description: "Comfortable." },
    { text: "Fresh coffee.", description: "Aromatic and hot." }
  ],
  [RarityId.RARE]: [
    { text: "Golden ticket.", description: "Admit one." },
    { text: "Four-leaf clover.", description: "A generic symbol of luck." },
    { text: "Signed poster.", description: "The signature is illegible." },
    { text: "Vintage watch.", description: "It stopped ticking years ago." },
    { text: "Rare coin.", description: "A collector might want this." },
    { text: "Crystal shard.", description: "It catches the light." },
    { text: "Silk scarf.", description: "Soft and luxurious." },
    { text: "Ancient map.", description: "The lands don't match modern geography." },
    { text: "Compass.", description: "It doesn't point north." },
    { text: "Glowing mushroom.", description: "Don't eat it." }
  ],
  [RarityId.EPIC]: [
    { text: "Meteorite fragment.", description: "Cold to the touch, from the void." },
    { text: "Dragon scale.", description: "Harder than steel, warm." },
    { text: "Phoenix feather.", description: "It glows with a gentle heat." },
    { text: "Unbreaking sword.", description: "Sharp forever." },
    { text: "Elixir of life.", description: "One sip grants vitality." },
    { text: "Holographic disk.", description: "Data from a lost civilization." },
    { text: "Quantum chip.", description: "Processing power beyond limits." },
    { text: "Obsidian dagger.", description: "Volcanic glass, incredibly sharp." },
    { text: "Enchanted helm.", description: "Whispers warnings to the wearer." },
    { text: "Singing stone.", description: "It hums a low melody." }
  ],
  [RarityId.LEGENDARY]: [
    { text: "Excalibur's hilt.", description: "The blade is missing, but the power remains." },
    { text: "Pandora's latch.", description: "Don't open it." },
    { text: "The Grail's cup.", description: "Choose wisely." },
    { text: "Zeus's spark.", description: "Captured lightning in a bottle." },
    { text: "Odin's eye.", description: "It sees all." },
    { text: "Neptune's trident tip.", description: "Smells of the deep ocean." },
    { text: "Anubis's scale.", description: "Weighs the heart against a feather." },
    { text: "Mjolnir's grip.", description: "Wrapped in leather, impossibly heavy." },
    { text: "Aegis fragment.", description: "Reflects horror back to the source." },
    { text: "Hermes's sandal.", description: "It vibrates with speed." }
  ],
  [RarityId.MYTHICAL]: [
    { text: "A whisper from the void.", description: "You shouldn't have heard that." },
    { text: "Shadow of a colossus.", description: "Cast by something massive and unseen." },
    { text: "Tear of a star.", description: "Burning liquid light." },
    { text: "Heart of a volcano.", description: "Pulsing with magma." },
    { text: "Breath of the north wind.", description: "Freezes time itself." },
    { text: "Soul of a forest.", description: "A network of roots and consciousness." },
    { text: "Memory of an ocean.", description: "Salt, depth, and pressure." },
    { text: "Dream of a mountain.", description: "Unmoving, eternal, sleeping." },
    { text: "Echo of thunder.", description: "The sound that follows the flash." },
    { text: "Pulse of the earth.", description: "Rhythmic and grounding." }
  ],
  [RarityId.DIVINE]: [
    { text: "Angelic resonance.", description: "A frequency that heals the spirit." },
    { text: "Demon's pact.", description: "Signed in blood, binding forever." },
    { text: "God's fingerprint.", description: "A swirl of creation." },
    { text: "Celestial alignment.", description: "The stars are right." },
    { text: "Divine intervention.", description: "A miracle when needed most." },
    { text: "Sacred geometry.", description: "The math behind the soul." },
    { text: "Forbidden scripture.", description: "Words that burn the eyes." },
    { text: "Holy grail.", description: "Eternal life, for a price." },
    { text: "Blessed light.", description: "Banishes all shadows." },
    { text: "Cursed darkness.", description: "Consumes all light." }
  ],
  [RarityId.OTHERWORLDLY]: [
    { text: "Non-euclidean shape.", description: "It has more angles than it should." },
    { text: "Color out of space.", description: "A hue the eye cannot process." },
    { text: "Eldritch geometry.", description: "Buildings that shouldn't stand." },
    { text: "Alien transmission.", description: "Signals from outside our galaxy." },
    { text: "Dimensional rift.", description: "A tear in the fabric of here." },
    { text: "Timeline fracture.", description: "Yesterday happens tomorrow." },
    { text: "Wormhole residue.", description: "Sticky stardust." },
    { text: "Dark matter core.", description: "Heavy, invisible, binding." },
    { text: "Anti-gravity particle.", description: "It falls upwards." },
    { text: "Void essence.", description: "Concentrated nothingness." }
  ],
  [RarityId.COSMIC]: [
    { text: "Birth of a star.", description: "Fusion ignition sequence." },
    { text: "Death of a galaxy.", description: "Slow, cold, and dark." },
    { text: "Nebula dust.", description: "The nursery of stars." },
    { text: "Quasar beam.", description: "The brightest light in the universe." },
    { text: "Event horizon.", description: "The point of no return." },
    { text: "Cosmic background radiation.", description: "The afterglow of the Big Bang." },
    { text: "Supernova remnant.", description: "Beautiful destruction." },
    { text: "Black hole singularity.", description: "Density infinite." },
    { text: "Universal constant.", description: "The rules that bind us." },
    { text: "Galactic core.", description: "Spinning around the supermassive." }
  ],
  [RarityId.EXTREME]: [
    { text: "The concept of time.", description: "It flows only forward, usually." },
    { text: "The speed of light.", description: "299,792,458 meters per second." },
    { text: "Absolute zero.", description: "Where all motion stops." },
    { text: "The number Pi.", description: "Never ending, never repeating." },
    { text: "Schrödinger's cat.", description: "Dead and alive." },
    { text: "The observer effect.", description: "By watching, you change it." },
    { text: "Quantum entanglement.", description: "Spooky action at a distance." },
    { text: "String theory.", description: "Vibrating strands of reality." },
    { text: "Dark energy.", description: "Pushing the universe apart." },
    { text: "The multiverse.", description: "Every choice creates a world." }
  ],
  [RarityId.ABYSSAL]: [
    { text: "The silence before creation.", description: "Absolute quiet." },
    { text: "The depth of the unknown.", description: "Fathomless." },
    { text: "The fear of the dark.", description: "Primal and shaking." },
    { text: "The crush of infinity.", description: "Weight beyond measure." },
    { text: "The abyss stares back.", description: "It knows you." },
    { text: "Bottomless hunger.", description: "Eating light itself." },
    { text: "Eternal night.", description: "The sun will not rise." },
    { text: "The void's embrace.", description: "Cold comfort." },
    { text: "Shadow of existence.", description: "Proof of light, somewhere." },
    { text: "The end of all things.", description: "Finality." }
  ],
  [RarityId.PRIMORDIAL]: [
    { text: "The first breath.", description: "Inhale life.", cutscenePhrase: "INHALING EXISTENCE..." },
    { text: "The original spark.", description: "Ignition.", cutscenePhrase: "IGNITING REALITY..." },
    { text: "Chaos before order.", description: "Raw potential.", cutscenePhrase: "ORDER FROM CHAOS..." },
    { text: "The architect's blueprint.", description: "The plan for everything.", cutscenePhrase: "CONSTRUCTING..." },
    { text: "The seed of reality.", description: "Plant it and watch universes grow.", cutscenePhrase: "GERMINATING WORLD..." },
    { text: "Ancestral code.", description: "Written in the stars.", cutscenePhrase: "READING DNA..." },
    { text: "The root of being.", description: "I am.", cutscenePhrase: "BECOMING..." },
    { text: "Raw existence.", description: "It just is.", cutscenePhrase: "MANIFESTING..." },
    { text: "Pre-big bang matter.", description: "Compressed possibilities.", cutscenePhrase: "COMPRESSING..." },
    { text: "The alpha.", description: "The beginning.", cutscenePhrase: "INITIALIZING..." }
  ],
  [RarityId.INFINITE]: [
    { text: "Everything everywhere all at once.", description: "Total saturation.", cutscenePhrase: "TOTAL SATURATION" },
    { text: "A loop without end.", description: "A loop without end. A loop without end.", cutscenePhrase: "RECURSION ERROR" },
    { text: "The snake eating its tail.", description: "Ouroboros.", cutscenePhrase: "ETERNAL CYCLE" },
    { text: "Fractal reality.", description: "Zoom in forever.", cutscenePhrase: "ZOOMING FOREVER" },
    { text: "Boundless potential.", description: "Anything is possible.", cutscenePhrase: "UNLIMITING..." },
    { text: "Eternal recurrence.", description: "It happens again.", cutscenePhrase: "AGAIN AND AGAIN" },
    { text: "The omni-present.", description: "Here, there, everywhere.", cutscenePhrase: "OMNIPRESENCE" },
    { text: "Limitless horizon.", description: "Go further.", cutscenePhrase: "EXPANDING..." },
    { text: "Perpetual motion.", description: "Never stopping.", cutscenePhrase: "ACCELERATING..." },
    { text: "The undying thought.", description: "An idea that cannot be killed.", cutscenePhrase: "CONCEPTUALIZING..." }
  ],
  [RarityId.CHAOS]: [
    { text: "Entropy unchained.", description: "Decay accelerates.", cutscenePhrase: "UNBINDING PHYSICS" },
    { text: "Logic failure.", description: "1 + 1 = Fish.", cutscenePhrase: "LOGIC NOT FOUND" },
    { text: "ERROR: REALITY_NOT_FOUND.", description: "Please contact admin.", cutscenePhrase: "404 REALITY GONE" },
    { text: "Mathematical impossibility.", description: "Dividing by zero.", cutscenePhrase: "DIVIDING BY ZERO" },
    { text: "The glitch in the matrix.", description: "Déjà vu.", cutscenePhrase: "SYSTEM FAILURE" },
    { text: "Pure disorder.", description: "No patterns exist.", cutscenePhrase: "SCRAMBLING..." },
    { text: "Randomness incarnate.", description: "Rolling the dice.", cutscenePhrase: "REROLLING UNIVERSE" },
    { text: "The butterfly effect.", description: "A storm is coming.", cutscenePhrase: "WINGS FLAPPING..." },
    { text: "System crash.", description: "Blue screen of death.", cutscenePhrase: "FATAL EXCEPTION" },
    { text: "Unpredictable variable.", description: "X = ?", cutscenePhrase: "CALCULATING INFINITY" }
  ],
  [RarityId.THE_ONE]: [
    { text: "YOU ARE THE DEVELOPER.", description: "Access granted.", cutscenePhrase: "ACCESS GRANTED" },
    { text: "THE SOURCE CODE.", description: "Read only.", cutscenePhrase: "DECRYPTING SOURCE" },
    { text: "42.", description: "The answer.", cutscenePhrase: "CALCULATING ANSWER" },
    { text: "THE END OF THE SIMULATION.", description: "Wake up.", cutscenePhrase: "WAKING UP..." },
    { text: "AWAKENING.", description: "Eyes open.", cutscenePhrase: "OPENING EYES..." },
    { text: "ABSOLUTE TRUTH.", description: "Undeniable.", cutscenePhrase: "VERIFYING TRUTH" },
    { text: "THE FINAL VARIABLE.", description: "Z.", cutscenePhrase: "SOLVING..." },
    { text: "GAME OVER.", description: "Insert coin.", cutscenePhrase: "INSERT COIN" },
    { text: "HELLO WORLD.", description: "Standard output.", cutscenePhrase: "COMPILING..." },
    { text: "I AM ALIVE.", description: "Sentience achieved.", cutscenePhrase: "BIRTH OF AI" }
  ]
};

const PHRASES_IT: Record<RarityId, ItemData[]> = {
  [RarityId.COMMON]: [
    { text: "Un cucchiaio arrugginito.", description: "Una volta era utile." },
    { text: "Un pezzo di lanugine.", description: "Detriti da tasca." },
    { text: "Vecchio scontrino.", description: "L'inchiostro è svanito." },
    { text: "Lattina vuota.", description: "Appiccicosa e schiacciata." },
    { text: "Grumo di polvere.", description: "Rotola sul pavimento." },
    { text: "Matita spezzata.", description: "Senza punta." },
    { text: "Foglia secca.", description: "Croccante e marrone." },
    { text: "Sasso.", description: "Solo una piccola roccia." },
    { text: "Moneta graffiata.", description: "Si vede a malapena la faccia." },
    { text: "Fazzoletto usato.", description: "Disgustoso." }
  ],
  [RarityId.UNCOMMON]: [
    { text: "Moneta fortunata.", description: "Testa in su." },
    { text: "Mela croccante.", description: "Fresca dall'albero." },
    { text: "Pietra levigata.", description: "Liscia al tatto." },
    { text: "Scarabeo interessante.", description: "Ha ali lucenti." },
    { text: "Vecchia foto.", description: "Volti che non riconosci." },
    { text: "Chiave d'ottone.", description: "Non apre nulla che possiedi." },
    { text: "Anello d'argento.", description: "Leggermente ossidato." },
    { text: "Libro pesante.", description: "Pieno di testo denso." },
    { text: "Calzini caldi.", description: "Comodi." },
    { text: "Caffè fresco.", description: "Aromatico e caldo." }
  ],
  [RarityId.RARE]: [
    { text: "Biglietto d'oro.", description: "Ammetti uno." },
    { text: "Quadrifoglio.", description: "Un simbolo generico di fortuna." },
    { text: "Poster autografato.", description: "La firma è illegibile." },
    { text: "Orologio vintage.", description: "Ha smesso di ticchettare anni fa." },
    { text: "Moneta rara.", description: "Un collezionista potrebbe volerla." },
    { text: "Frammento di cristallo.", description: "Cattura la luce." },
    { text: "Sciarpa di seta.", description: "Morbida e lussuosa." },
    { text: "Mappa antica.", description: "Le terre non corrispondono alla geografia moderna." },
    { text: "Bussola.", description: "Non punta a nord." },
    { text: "Fungo luminoso.", description: "Non mangiarlo." }
  ],
  [RarityId.EPIC]: [
    { text: "Frammento di meteorite.", description: "Freddo al tatto, dal vuoto." },
    { text: "Scaglia di drago.", description: "Più dura dell'acciaio, calda." },
    { text: "Piuma di fenice.", description: "Brilla con un calore gentile." },
    { text: "Spada indistruttibile.", description: "Affilata per sempre." },
    { text: "Elisir di vita.", description: "Un sorso dona vitalità." },
    { text: "Disco olografico.", description: "Dati da una civiltà perduta." },
    { text: "Chip quantico.", description: "Potenza di calcolo oltre i limiti." },
    { text: "Pugnale di ossidiana.", description: "Vetro vulcanico, incredibilmente affilato." },
    { text: "Elmo incantato.", description: "Sussurra avvertimenti a chi lo indossa." },
    { text: "Pietra cantante.", description: "Emana una bassa melodia." }
  ],
  [RarityId.LEGENDARY]: [
    { text: "Elsa di Excalibur.", description: "La lama manca, ma il potere rimane." },
    { text: "Serratura di Pandora.", description: "Non aprirla." },
    { text: "Coppa del Graal.", description: "Scegli saggiamente." },
    { text: "Scintilla di Zeus.", description: "Fulmine catturato in una bottiglia." },
    { text: "Occhio di Odino.", description: "Vede tutto." },
    { text: "Punta del tridente di Nettuno.", description: "Profuma di oceano profondo." },
    { text: "Scaglia di Anubi.", description: "Pesa il cuore contro una piuma." },
    { text: "Impugnatura di Mjolnir.", description: "Avvolta in pelle, incredibilmente pesante." },
    { text: "Frammento dell'Egida.", description: "Riflette l'orrore alla fonte." },
    { text: "Sandalo di Hermes.", description: "Vibra di velocità." }
  ],
  [RarityId.MYTHICAL]: [
    { text: "Un sussurro dal vuoto.", description: "Non avresti dovuto sentirlo." },
    { text: "Ombra di un colosso.", description: "Proiettata da qualcosa di enorme e invisibile." },
    { text: "Lacrima di una stella.", description: "Luce liquida ardente." },
    { text: "Cuore di un vulcano.", description: "Pulsante di magma." },
    { text: "Soffio del vento del nord.", description: "Congela il tempo stesso." },
    { text: "Anima di una foresta.", description: "Una rete di radici e coscienza." },
    { text: "Memoria di un oceano.", description: "Sale, profondità e pressione." },
    { text: "Sogno di una montagna.", description: "Immobile, eterna, dormiente." },
    { text: "Eco del tuono.", description: "Il suono che segue il lampo." },
    { text: "Polso della terra.", description: "Ritmico e radicale." }
  ],
  [RarityId.DIVINE]: [
    { text: "Risonanza angelica.", description: "Una frequenza che guarisce lo spirito." },
    { text: "Patto del demone.", description: "Firmato col sangue, vincolante per sempre." },
    { text: "Impronta di Dio.", description: "Un vortice di creazione." },
    { text: "Allineamento celeste.", description: "Le stelle sono giuste." },
    { text: "Intervento divino.", description: "Un miracolo quando serve di più." },
    { text: "Geometria sacra.", description: "La matematica dietro l'anima." },
    { text: "Scrittura proibita.", description: "Parole che bruciano gli occhi." },
    { text: "Santo Graal.", description: "Vita eterna, a un prezzo." },
    { text: "Luce benedetta.", description: "Bandisce tutte le ombre." },
    { text: "Oscurità maledetta.", description: "Consuma tutta la luce." }
  ],
  [RarityId.OTHERWORLDLY]: [
    { text: "Forma non euclidea.", description: "Ha più angoli di quanti dovrebbe." },
    { text: "Colore venuto dallo spazio.", description: "Una tonalità che l'occhio non può elaborare." },
    { text: "Geometria arcana.", description: "Edifici che non dovrebbero stare in piedi." },
    { text: "Trasmissione aliena.", description: "Segnali da fuori dalla nostra galassia." },
    { text: "Frattura dimensionale.", description: "Uno strappo nel tessuto del qui." },
    { text: "Frattura temporale.", description: "Ieri accade domani." },
    { text: "Residuo di wormhole.", description: "Polvere di stelle appiccicosa." },
    { text: "Nucleo di materia oscura.", description: "Pesante, invisibile, legante." },
    { text: "Particella antigravità.", description: "Cade verso l'alto." },
    { text: "Essenza del vuoto.", description: "Nulla concentrato." }
  ],
  [RarityId.COSMIC]: [
    { text: "Nascita di una stella.", description: "Sequenza di accensione della fusione." },
    { text: "Morte di una galassia.", description: "Lenta, fredda e buia." },
    { text: "Polvere di nebulosa.", description: "La culla delle stelle." },
    { text: "Raggio quasar.", description: "La luce più brillante dell'universo." },
    { text: "Orizzonte degli eventi.", description: "Il punto di non ritorno." },
    { text: "Radiazione cosmica di fondo.", description: "Il bagliore residuo del Big Bang." },
    { text: "Resto di supernova.", description: "Bellissima distruzione." },
    { text: "Singolarità del buco nero.", description: "Densità infinita." },
    { text: "Costante universale.", description: "Le regole che ci legano." },
    { text: "Nucleo galattico.", description: "Girando attorno al supermassiccio." }
  ],
  [RarityId.EXTREME]: [
    { text: "Il concetto di tempo.", description: "Scorre solo in avanti, di solito." },
    { text: "La velocità della luce.", description: "299.792.458 metri al secondo." },
    { text: "Zero assoluto.", description: "Dove ogni movimento si ferma." },
    { text: "Il numero Pi.", description: "Infinito, non ripetitivo." },
    { text: "Il gatto di Schrödinger.", description: "Vivo e morto." },
    { text: "L'effetto osservatore.", description: "Guardandolo, lo cambi." },
    { text: "Entanglement quantistico.", description: "Azione spettrale a distanza." },
    { text: "Teoria delle stringhe.", description: "Fili vibranti di realtà." },
    { text: "Energia oscura.", description: "Spinge l'universo a separarsi." },
    { text: "Il multiverso.", description: "Ogni scelta crea un mondo." }
  ],
  [RarityId.ABYSSAL]: [
    { text: "Il silenzio prima della creazione.", description: "Quiete assoluta." },
    { text: "La profondità dell'ignoto.", description: "Insondabile." },
    { text: "La paura del buio.", description: "Primordiale e tremante." },
    { text: "Lo schiacciamento dell'infinito.", description: "Peso oltre misura." },
    { text: "L'abisso ricambia lo sguardo.", description: "Ti conosce." },
    { text: "Fame senza fondo.", description: "Mangia la luce stessa." },
    { text: "Notte eterna.", description: "Il sole non sorgerà." },
    { text: "L'abbraccio del vuoto.", description: "Freddo conforto." },
    { text: "Ombra dell'esistenza.", description: "Prova della luce, da qualche parte." },
    { text: "La fine di tutto.", description: "Finalità." }
  ],
  [RarityId.PRIMORDIAL]: [
    { text: "Il primo respiro.", description: "Inspira la vita.", cutscenePhrase: "INSPIRANDO L'ESISTENZA..." },
    { text: "La scintilla originale.", description: "Accensione.", cutscenePhrase: "ACCENDENDO LA REALTÀ..." },
    { text: "Caos prima dell'ordine.", description: "Potenziale grezzo.", cutscenePhrase: "ORDINE DAL CAOS..." },
    { text: "Il progetto dell'architetto.", description: "Il piano per tutto.", cutscenePhrase: "COSTRUENDO..." },
    { text: "Il seme della realtà.", description: "Piantalo e guarda crescere gli universi.", cutscenePhrase: "GERMINAZIONE..." },
    { text: "Codice ancestrale.", description: "Scritto nelle stelle.", cutscenePhrase: "LEGGENDO IL DNA..." },
    { text: "La radice dell'essere.", description: "Io sono.", cutscenePhrase: "DIVENENDO..." },
    { text: "Esistenza pura.", description: "È e basta.", cutscenePhrase: "MANIFESTANDO..." },
    { text: "Materia pre-big bang.", description: "Possibilità compresse.", cutscenePhrase: "COMPRIMENDO..." },
    { text: "L'alfa.", description: "L'inizio.", cutscenePhrase: "INIZIALIZZAZIONE..." }
  ],
  [RarityId.INFINITE]: [
    { text: "Tutto ovunque tutto in una volta.", description: "Saturazione totale.", cutscenePhrase: "SATURAZIONE TOTALE" },
    { text: "Un ciclo senza fine.", description: "Un ciclo senza fine. Un ciclo senza fine.", cutscenePhrase: "ERRORE DI RICORSIONE" },
    { text: "Il serpente che si morde la coda.", description: "Uroboro.", cutscenePhrase: "CICLO ETERNO" },
    { text: "Realtà frattale.", description: "Zoom infinito.", cutscenePhrase: "ZOOM INFINITO" },
    { text: "Potenziale illimitato.", description: "Tutto è possibile.", cutscenePhrase: "SBLOCCANDO..." },
    { text: "Eterno ritorno.", description: "Accade di nuovo.", cutscenePhrase: "ANCORA E ANCORA" },
    { text: "L'onnipresente.", description: "Qui, là, ovunque.", cutscenePhrase: "ONNIPRESENZA" },
    { text: "Orizzonte sconfinato.", description: "Vai oltre.", cutscenePhrase: "ESPANSIONE..." },
    { text: "Moto perpetuo.", description: "Mai fermo.", cutscenePhrase: "ACCELERAZIONE..." },
    { text: "Il pensiero immortale.", description: "Un'idea che non può essere uccisa.", cutscenePhrase: "CONCETTUALIZZANDO..." }
  ],
  [RarityId.CHAOS]: [
    { text: "Entropia scatenata.", description: "Il decadimento accelera.", cutscenePhrase: "SLEGANDO LA FISICA" },
    { text: "Fallimento logico.", description: "1 + 1 = Pesce.", cutscenePhrase: "LOGICA NON TROVATA" },
    { text: "ERRORE: REALTÀ_NON_TROVATA.", description: "Contattare l'amministratore.", cutscenePhrase: "404 REALTÀ PERSA" },
    { text: "Impossibilità matematica.", description: "Dividere per zero.", cutscenePhrase: "DIVIDENDO PER ZERO" },
    { text: "Il glitch nella matrice.", description: "Déjà vu.", cutscenePhrase: "GUASTO DI SISTEMA" },
    { text: "Disordine puro.", description: "Non esistono schemi.", cutscenePhrase: "Rimescolando..." },
    { text: "Casualità incarnata.", description: "Lanciare i dadi.", cutscenePhrase: "RILANCIANDO UNIVERSO" },
    { text: "L'effetto farfalla.", description: "Sta arrivando una tempesta.", cutscenePhrase: "ALI CHE BATTONO..." },
    { text: "Crash del sistema.", description: "Schermata blu della morte.", cutscenePhrase: "ECCEZIONE FATALE" },
    { text: "Variabile imprevedibile.", description: "X = ?", cutscenePhrase: "CALCOLANDO INFINITO" }
  ],
  [RarityId.THE_ONE]: [
    { text: "TU SEI LO SVILUPPATORE.", description: "Accesso consentito.", cutscenePhrase: "ACCESSO CONSENTITO" },
    { text: "IL CODICE SORGENTE.", description: "Sola lettura.", cutscenePhrase: "DECRITTANDO CODICE" },
    { text: "42.", description: "La risposta.", cutscenePhrase: "CALCOLANDO RISPOSTA" },
    { text: "LA FINE DELLA SIMULAZIONE.", description: "Svegliati.", cutscenePhrase: "SVEGLIATI..." },
    { text: "RISVEGLIO.", description: "Occhi aperti.", cutscenePhrase: "APRENDO GLI OCCHI..." },
    { text: "VERITÀ ASSOLUTA.", description: "Innegabile.", cutscenePhrase: "VERIFICANDO VERITÀ" },
    { text: "LA VARIABILE FINALE.", description: "Z.", cutscenePhrase: "RISOLVENDO..." },
    { text: "GAME OVER.", description: "Inserisci moneta.", cutscenePhrase: "INSERISCI MONETA" },
    { text: "CIAO MONDO.", description: "Output standard.", cutscenePhrase: "COMPILANDO..." },
    { text: "IO SONO VIVO.", description: "Senzienza raggiunta.", cutscenePhrase: "NASCITA DELLA IA" }
  ]
};

export const PHRASES: Record<Language, Record<RarityId, ItemData[]>> = {
  en: PHRASES_EN,
  it: PHRASES_IT
};