import { Fish } from '../../types';

export const FISH: Fish[] = [
    // --- TIER 1: SURFACE (1-10) ---
    { id: 1, name: "Digital Guppy", description: "A small, low-poly fish.", probability: 2, color: "text-orange-300", glowColor: "#fdba74", tierName: "Common" },
    { id: 2, name: "Byte Minnow", description: "8 of these make a snack.", probability: 3, color: "text-blue-300", glowColor: "#93c5fd", tierName: "Common" },
    { id: 3, name: "Pixel Carp", description: "Scales look like squares.", probability: 4, color: "text-yellow-600", glowColor: "#ca8a04", tierName: "Common" },
    { id: 4, name: "Static Trout", description: "Makes a buzzing noise.", probability: 5, color: "text-neutral-400", glowColor: "#a3a3a3", tierName: "Common" },
    { id: 5, name: "Neon Tetra", description: "Glows in the dark web.", probability: 6, color: "text-fuchsia-400", glowColor: "#e879f9", tierName: "Common" },
    { id: 6, name: "Binary Bass", description: "01000010 01100001 01110011 01110011", probability: 8, color: "text-green-700", glowColor: "#15803d", tierName: "Common" },
    { id: 7, name: "Glitch Goldfish", description: "Flickers between orange and void.", probability: 10, color: "text-amber-500 animate-pulse", glowColor: "#f59e0b", tierName: "Common" },
    { id: 8, name: "Data Crab", description: "Moves sideways through the firewall.", probability: 12, color: "text-red-400", glowColor: "#f87171", tierName: "Common" },
    { id: 9, name: "Rusty Can", description: "Someone threw this in the server pool.", probability: 15, color: "text-stone-500", glowColor: "#78716c", tierName: "Trash" },
    { id: 10, name: "Old Boot", description: "Boot.exe has stopped working.", probability: 20, color: "text-yellow-900", glowColor: "#451a03", tierName: "Trash" },
    // --- TIER 2: REEF (11-20) ---
    { id: 11, name: "Cyber Salmon", description: "Swims upstream against the data stream.", probability: 25, color: "text-rose-400", glowColor: "#fb7185", tierName: "Uncommon" },
    { id: 12, name: "Electric Eel", description: "Powered by USB-C.", probability: 30, color: "text-yellow-400", glowColor: "#facc15", tierName: "Uncommon" },
    { id: 13, name: "Source Code Squid", description: "Ink is pure black #000000.", probability: 40, color: "text-black bg-white px-1", glowColor: "#ffffff", tierName: "Uncommon" },
    { id: 14, name: "Firewall Puffer", description: "Expands to block ports.", probability: 50, color: "text-red-600", glowColor: "#dc2626", tierName: "Uncommon" },
    { id: 15, name: "Search Engine Shark", description: "Smells your browser history.", probability: 60, color: "text-blue-600", glowColor: "#2563eb", tierName: "Predator" },
    { id: 16, name: "Encrypted Ray", description: "Needs a key to see clearly.", probability: 75, color: "text-neutral-300 blur-[1px]", glowColor: "#d4d4d4", tierName: "Rare" },
    { id: 17, name: "GPU Jellyfish", description: "Processes graphics while floating.", probability: 100, color: "text-cyan-400", glowColor: "#22d3ee", tierName: "Rare" },
    { id: 18, name: "Fiber Optic Flounder", description: "Transmits light through its body.", probability: 125, color: "text-white", glowColor: "#ffffff", tierName: "Rare" },
    { id: 19, name: "Packet Loss Pike", description: "Now you see it, now you don't.", probability: 150, color: "text-neutral-500 animate-pulse", glowColor: "#737373", tierName: "Rare" },
    { id: 20, name: "Cookie Cutter Shark", description: "Steals your login cookies.", probability: 200, color: "text-orange-800", glowColor: "#9a3412", tierName: "Rare" },
    // --- TIER 3: DEEP (21-30) ---
    { id: 21, name: "Deep Web Angler", description: "Lures prey with a fake link.", probability: 300, color: "text-purple-400", glowColor: "#c084fc", tierName: "Deep" },
    { id: 22, name: "VPN Viperfish", description: "Masks its location.", probability: 400, color: "text-green-400", glowColor: "#4ade80", tierName: "Deep" },
    { id: 23, name: "Blobfish.png", description: "Low resolution compression artifacts.", probability: 500, color: "text-pink-300 blur-sm", glowColor: "#f9a8d4", tierName: "Deep" },
    { id: 24, name: "Blockchain Barracuda", description: "Verified ownership of bite marks.", probability: 600, color: "text-yellow-600", glowColor: "#ca8a04", tierName: "Crypto" },
    { id: 25, name: "Mining Rig Marlin", description: "Generates heat.", probability: 750, color: "text-red-500", glowColor: "#ef4444", tierName: "Crypto" },
    { id: 26, name: "Phishing Piranha", description: "Sends fake emails.", probability: 1000, color: "text-red-700", glowColor: "#b91c1c", tierName: "Malware" },
    { id: 27, name: "Trojan Seahorse", description: "Looks like a gift.", probability: 1250, color: "text-amber-700", glowColor: "#b45309", tierName: "Malware" },
    { id: 28, name: "Worm Eel", description: "Self-replicating.", probability: 1500, color: "text-lime-600", glowColor: "#65a30d", tierName: "Malware" },
    { id: 29, name: "Spyware Starfish", description: "Sticks to you and watches.", probability: 2000, color: "text-indigo-500", glowColor: "#6366f1", tierName: "Malware" },
    { id: 30, name: "Ransomware Ray", description: "Encrypts your other fish.", probability: 2500, color: "text-red-900", glowColor: "#7f1d1d", tierName: "Malware" },
    // --- TIER 4: ABYSS (31-40) ---
    { id: 31, name: "Void Leviathan", description: "Massive entity of null data.", probability: 5000, color: "text-violet-950 drop-shadow-[0_0_10px_#4c1d95]", glowColor: "#4c1d95", tierName: "Abyssal" },
    { id: 32, name: "Null Pointer Nautilus", description: "Points to nothing.", probability: 7500, color: "text-neutral-600", glowColor: "#525252", tierName: "Abyssal" },
    { id: 33, name: "404 Fish", description: "Species not found.", probability: 10000, color: "text-neutral-100", glowColor: "#f5f5f5", tierName: "Error" },
    { id: 34, name: "Infinite Loop Loach", description: "Swims in circles forever.", probability: 15000, color: "text-teal-400", glowColor: "#2dd4bf", tierName: "Error" },
    { id: 35, name: "Kernel Panic Kraken", description: "Crashes the OS on surfacing.", probability: 25000, color: "text-red-600 animate-pulse", glowColor: "#dc2626", tierName: "System" },
    { id: 36, name: "Root Access Ray", description: "Grants full control.", probability: 40000, color: "text-green-500", glowColor: "#22c55e", tierName: "System" },
    { id: 37, name: "Ghost in the Shellfish", description: "Possessed by AI.", probability: 60000, color: "text-cyan-200", glowColor: "#a5f3fc", tierName: "AI" },
    { id: 38, name: "Neural Net Narwhal", description: "Tusk is an antenna.", probability: 80000, color: "text-purple-500", glowColor: "#a855f7", tierName: "AI" },
    { id: 39, name: "Algorithm Algae", description: "Curates your feed.", probability: 100000, color: "text-emerald-600", glowColor: "#059669", tierName: "AI" },
    { id: 40, name: "Singularity Shark", description: "Event horizon in its mouth.", probability: 150000, color: "text-black bg-white px-1 animate-pulse", glowColor: "#000000", tierName: "Cosmic" },
    // --- TIER 5: LEGENDARY (41-50) ---
    { id: 41, name: "The Glitch Ness Monster", description: "A myth made of bugs.", probability: 250000, color: "text-fuchsia-500 animate-bounce", glowColor: "#d946ef", tierName: "Cryptid" },
    { id: 42, name: "Cthulhu.exe", description: "Do not run this file.", probability: 500000, color: "text-green-900 drop-shadow-[0_0_15px_#14532d]", glowColor: "#14532d", tierName: "Eldritch" },
    { id: 43, name: "Moby Dick (PDF)", description: "The entire book in one fish.", probability: 750000, color: "text-white", glowColor: "#ffffff", tierName: "Literature" },
    { id: 44, name: "Golden Magikarp", description: "Useless but shiny.", probability: 1000000, color: "text-yellow-400 drop-shadow-[0_0_10px_#facc15]", glowColor: "#facc15", tierName: "Pokemon" },
    { id: 45, name: "Time Stream Trout", description: "Caught yesterday.", probability: 2000000, color: "text-blue-400", glowColor: "#60a5fa", tierName: "Temporal" },
    { id: 46, name: "Schrödinger's Catfish", description: "Alive and dead until caught.", probability: 5000000, color: "text-neutral-400", glowColor: "#a3a3a3", tierName: "Quantum" },
    { id: 47, name: "The Cloud Whale", description: "Stores everyone's photos.", probability: 10000000, color: "text-sky-200 cloud-texture", glowColor: "#bae6fd", tierName: "Server" },
    { id: 48, name: "Mainframe Megalodon", description: "Apex predator of the net.", probability: 25000000, color: "text-red-950 animate-pulse", glowColor: "#450a0a", tierName: "Boss" },
    { id: 49, name: "Zero Day Exploit", description: "No patch available.", probability: 50000000, color: "text-red-500 font-mono", glowColor: "#ef4444", tierName: "Critical" },
    { id: 50, name: "Developers Rubber Duck", description: "It solves all bugs.", probability: 100000000, color: "text-yellow-300 animate-spin", glowColor: "#fde047", tierName: "Dev" },
    // --- TIER 6: SKY (51-60) ---
    { id: 51, name: "Cloud Carp", description: "Swims in the cumulus.", probability: 150000000, color: "text-slate-200", glowColor: "#e2e8f0", tierName: "Sky" },
    { id: 52, name: "Rain Ray", description: "Drips constantly.", probability: 200000000, color: "text-blue-400", glowColor: "#60a5fa", tierName: "Sky" },
    { id: 53, name: "Thunder Trout", description: "Loudest fish in the sea.", probability: 250000000, color: "text-yellow-400 animate-pulse", glowColor: "#facc15", tierName: "Sky" },
    { id: 54, name: "Wind Whale", description: "Floats on a breeze.", probability: 300000000, color: "text-cyan-100", glowColor: "#cffafe", tierName: "Sky" },
    { id: 55, name: "Solar Salmon", description: "Swims up light beams.", probability: 350000000, color: "text-orange-400", glowColor: "#fb923c", tierName: "Sky" },
    { id: 56, name: "Starfish (Literal)", description: "Five points, burning hot.", probability: 400000000, color: "text-yellow-200", glowColor: "#fef08a", tierName: "Sky" },
    { id: 57, name: "Moon Jelly", description: "Controls the tides.", probability: 450000000, color: "text-indigo-200", glowColor: "#c7d2fe", tierName: "Sky" },
    { id: 58, name: "Aurora Angler", description: "Lights up the north.", probability: 500000000, color: "text-green-400", glowColor: "#4ade80", tierName: "Sky" },
    { id: 59, name: "Vacuum Viper", description: "Breathes nothing.", probability: 600000000, color: "text-neutral-800", glowColor: "#262626", tierName: "Sky" },
    { id: 60, name: "Comet Cod", description: "Returns every 76 years.", probability: 700000000, color: "text-cyan-300", glowColor: "#67e8f9", tierName: "Sky" },
    // --- TIER 7: MAGMA (61-70) ---
    { id: 61, name: "Lava Lamprey", description: "Sucks heat.", probability: 800000000, color: "text-red-600", glowColor: "#dc2626", tierName: "Magma" },
    { id: 62, name: "Obsidian Orca", description: "Sharp skin.", probability: 900000000, color: "text-purple-950", glowColor: "#3b0764", tierName: "Magma" },
    { id: 63, name: "Magma Minnow", description: "Tiny spark.", probability: 1000000000, color: "text-orange-500", glowColor: "#f97316", tierName: "Magma" },
    { id: 64, name: "Ash Anchovy", description: "Tastes burnt.", probability: 1200000000, color: "text-stone-500", glowColor: "#78716c", tierName: "Magma" },
    { id: 65, name: "Fire Flounder", description: "Flat and hot.", probability: 1400000000, color: "text-red-500", glowColor: "#ef4444", tierName: "Magma" },
    { id: 66, name: "Brimstone Bass", description: "Smells like sulfur.", probability: 1600000000, color: "text-yellow-600", glowColor: "#ca8a04", tierName: "Magma" },
    { id: 67, name: "Thermal Tetra", description: "Seeks heat sources.", probability: 1800000000, color: "text-rose-400", glowColor: "#fb7185", tierName: "Magma" },
    { id: 68, name: "Pyro Piranha", description: "Boils the water.", probability: 2000000000, color: "text-orange-600 animate-pulse", glowColor: "#ea580c", tierName: "Magma" },
    { id: 69, name: "Cinder Crab", description: "Walks on coals.", probability: 2500000000, color: "text-stone-800", glowColor: "#292524", tierName: "Magma" },
    { id: 70, name: "Molten Marlin", description: "Liquid metal body.", probability: 3000000000, color: "text-red-400", glowColor: "#f87171", tierName: "Magma" },
    // --- TIER 8: DREAM (71-80) ---
    { id: 71, name: "Nightmare Eel", description: "You can't wake up.", probability: 3500000000, color: "text-black bg-white px-1", glowColor: "#000000", tierName: "Dream" },
    { id: 72, name: "Lucid Lobster", description: "It knows it's a lobster.", probability: 4000000000, color: "text-blue-300", glowColor: "#93c5fd", tierName: "Dream" },
    { id: 73, name: "Sleep Shark", description: "Never stops moving.", probability: 4500000000, color: "text-indigo-400", glowColor: "#818cf8", tierName: "Dream" },
    { id: 74, name: "REM Ray", description: "Rapid Eye Movement.", probability: 5000000000, color: "text-violet-400", glowColor: "#a78bfa", tierName: "Dream" },
    { id: 75, name: "Subconscious Squid", description: "Deepest thoughts.", probability: 6000000000, color: "text-purple-600", glowColor: "#9333ea", tierName: "Dream" },
    { id: 76, name: "Deja Vu Dory", description: "Have I caught this before?", probability: 7000000000, color: "text-cyan-500", glowColor: "#06b6d4", tierName: "Dream" },
    { id: 77, name: "Memory Mackerel", description: "Don't forget.", probability: 8000000000, color: "text-amber-300", glowColor: "#fcd34d", tierName: "Dream" },
    { id: 78, name: "Fantasy Fluke", description: "Impossible anatomy.", probability: 9000000000, color: "text-pink-400", glowColor: "#f472b6", tierName: "Dream" },
    { id: 79, name: "Illusion Ilisha", description: "Not really there.", probability: 10000000000, color: "text-white blur-[1px]", glowColor: "#ffffff", tierName: "Dream" },
    { id: 80, name: "Trance Tuna", description: "Hypnotic scales.", probability: 12000000000, color: "text-emerald-400 animate-pulse", glowColor: "#34d399", tierName: "Dream" },
    // --- TIER 9: ABSTRACT (81-90) ---
    { id: 81, name: "Concept Cod", description: "The idea of a fish.", probability: 15000000000, color: "text-gray-400", glowColor: "#9ca3af", tierName: "Abstract" },
    { id: 82, name: "Idea Isopod", description: "Crawls into your mind.", probability: 18000000000, color: "text-yellow-100", glowColor: "#fef9c3", tierName: "Abstract" },
    { id: 83, name: "Thought Trout", description: "Swimming upstream.", probability: 21000000000, color: "text-blue-200", glowColor: "#bfdbfe", tierName: "Abstract" },
    { id: 84, name: "Philosophy Puffer", description: "Full of hot air.", probability: 25000000000, color: "text-orange-300", glowColor: "#fdba74", tierName: "Abstract" },
    { id: 85, name: "Logic Loach", description: "Follows the rules.", probability: 30000000000, color: "text-green-600", glowColor: "#16a34a", tierName: "Abstract" },
    { id: 86, name: "Reason Ray", description: "Makes sense.", probability: 35000000000, color: "text-teal-500", glowColor: "#14b8a6", tierName: "Abstract" },
    { id: 87, name: "Wisdom Whale", description: "Knows everything.", probability: 40000000000, color: "text-indigo-800", glowColor: "#3730a3", tierName: "Abstract" },
    { id: 88, name: "Knowledge Koi", description: "Swimming in data.", probability: 50000000000, color: "text-red-500", glowColor: "#ef4444", tierName: "Abstract" },
    { id: 89, name: "Truth Tetra", description: "Cannot lie.", probability: 60000000000, color: "text-white drop-shadow-md", glowColor: "#ffffff", tierName: "Abstract" },
    { id: 90, name: "Fact Flounder", description: "Hard evidence.", probability: 75000000000, color: "text-stone-600", glowColor: "#57534e", tierName: "Abstract" },
    // --- TIER 10: META (91-100) ---
    { id: 91, name: "Clickbait Catfish", description: "You won't believe this!", probability: 100000000000, color: "text-red-600 font-bold", glowColor: "#dc2626", tierName: "Meta" },
    { id: 92, name: "Viral Video Viper", description: "Trending now.", probability: 125000000000, color: "text-purple-500", glowColor: "#a855f7", tierName: "Meta" },
    { id: 93, name: "Meme Minnow", description: "Dank.", probability: 150000000000, color: "text-green-500", glowColor: "#22c55e", tierName: "Meta" },
    { id: 94, name: "Stream Sniper Shark", description: "Watching your screen.", probability: 200000000000, color: "text-blue-600", glowColor: "#2563eb", tierName: "Meta" },
    { id: 95, name: "Lag Lobster", description: "Moves... very... slow...", probability: 250000000000, color: "text-neutral-500", glowColor: "#737373", tierName: "Meta" },
    { id: 96, name: "Buff Bass", description: "Stats increased.", probability: 300000000000, color: "text-orange-600", glowColor: "#ea580c", tierName: "Meta" },
    { id: 97, name: "Nerf Narwhal", description: "Stats decreased.", probability: 400000000000, color: "text-blue-300", glowColor: "#93c5fd", tierName: "Meta" },
    { id: 98, name: "Patch Note Piranha", description: "Changes everything.", probability: 500000000000, color: "text-yellow-500", glowColor: "#eab308", tierName: "Meta" },
    { id: 99, name: "DLC Dolphin", description: "Downloadable Content.", probability: 750000000000, color: "text-pink-500", glowColor: "#ec4899", tierName: "Meta" },
    { id: 100, name: "Microtransaction Manta", description: "$0.99 to swim.", probability: 1000000000000, color: "text-green-400 animate-pulse", glowColor: "#4ade80", tierName: "Meta" }
];
